SELECT ?stationId ?adjacentStationId ?lineId
WHERE
{
  ?stationId wdt:P31 wd:Q928830. # instance of = metro station
  ?stationId wdt:P16 wd:Q50716. # transport network = Paris Métro

  ?stationId wdt:P5817 wd:Q55654238. # state of use = in use
  ?adjacentStationId wdt:P5817 wd:Q55654238. # state of use = in use
  ?lineId wdt:P5817 wd:Q55654238. # state of use = in use

  ?stationId p:P197 ?statement.
  ?statement
    ps:P197 ?adjacentStationId;
    pq:P81 ?lineId.

  # Ensure adjacent station is on the same line (fix this)
  ?stationId wdt:P81 ?lineId.
  ?adjacentStationId wdt:P81 ?lineId.
}
