SELECT DISTINCT ?id ?name ?color
WHERE {
  BIND(wd:{subway} as ?transportNetwork)

  ?id wdt:P31/wdt:P279*/wdt:P361* wd:Q5503. # subclass* part of* instance of = rapid transit
  ?id wdt:P16 ?transportNetwork. # transport network
  ?id wdt:P5817 wd:Q55654238. # state of use = in use

  ?id wdt:P465 ?color.

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "mul,en,fr".
  
    ?id rdfs:label ?name
  }
}
