SELECT ?qid ?name ?coords
WHERE {
  BIND(wd:{subway} as ?transportNetwork)

  ?qid wdt:P31/wdt:P279* wd:Q928830. # subclass* instance of = metro station
  ?qid wdt:P16 ?transportNetwork. # transport network
  ?qid wdt:P5817 wd:Q55654238. # state of use = in use

  ?qid wdt:P625 ?coords.

  # TODO: add interchange station (P833)?

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "mul,en,fr".
  
    ?qid rdfs:label ?name.
  }
}
